//#include "contiki.h"


#ifndef LEACH_CONF
#define LEACH_CONF

#define CLOCK_SECOND 125  //  prescaler = /1024, 125*125 = 16000000mhz
#define CLOCK_CONF_SECOND 125

#define debug

#ifdef debug

#define RECLUSTER_TIME  10  * CLOCK_SECOND
#define CHOOSE_CLUSTERHEAD_TIME  10  * CLOCK_SECOND
#define WAIT_FOR_SCHEDULE_TIME  10  * CLOCK_SECOND
//#define TOTAL_RUN_TIME  1 * 60 * CLOCK_SECOND // n minutes times 60 seconds
#define TOTAL_RUN_TIME  20 * CLOCK_SECOND
#define WATCHDOG TOTAL_RUN_TIME * 2

#else

#define RECLUSTER_TIME  10  * CLOCK_SECOND
#define CHOOSE_CLUSTERHEAD_TIME  10  * CLOCK_SECOND
#define WAIT_FOR_SCHEDULE_TIME  10  * CLOCK_SECOND
//#define TOTAL_RUN_TIME  1 * 60 * CLOCK_SECOND // n minutes times 60 seconds
#define TOTAL_RUN_TIME  20 * CLOCK_SECOND


#endif	
	
	
#define CHANCE_OF_BEING_CH 30	


#define CHANNEL RF_CHANNEL

#define MIN_NEXT_READING_TIME 10 * CLOCK_SECOND
#define MAX_NEXT_READING_TIME 30 * CLOCK_SECOND
//#define MAX_NEXT_READING_TIME 32767   //5*60*CLOCK_SECOND

#define MIN_SEND_TIME 1 * CLOCK_SECOND

#define NUMBER_OF_MESSAGES_PER_ROUND 5

#endif
